# Chạy app trỏ API production (VPS) — emulator hoặc máy thật
Set-Location $PSScriptRoot\..

$envContent = @"
# Auto-generated by run_prod.ps1
API_BASE_URL=https://api.healthpath.com.vn
JWT_ISSUER=healthpath
GOOGLE_CLIENT_ID=340998906895-9vtgmn1h93kfl19nndfp9h2rr90eovkq.apps.googleusercontent.com
FACEBOOK_APP_ID=1271647791434810
FACEBOOK_CLIENT_TOKEN=000e12769aea1dea64171479f8ba10eb
FCM_ENABLED=true
"@

Set-Content -Path .env -Value $envContent -Encoding utf8
Write-Host ">>> .env -> https://api.healthpath.com.vn" -ForegroundColor Green

flutter pub get
flutter run
