# Ghi sẵn URL backend vào .env rồi chạy (tiện khi đổi emulator / Windows)
param(
    [ValidateSet('android', 'windows', 'ios', 'device')]
    [string]$Platform = 'android',
    [string]$DeviceIp = '192.168.1.100',
    [int]$Port = 7232,
    [switch]$UseHttp
)

Set-Location $PSScriptRoot\..

$scheme = if ($UseHttp) { 'http' } else { 'https' }
$apiBaseUrl = switch ($Platform) {
    'android' { "${scheme}://10.0.2.2:${Port}" }
    'windows' { "${scheme}://localhost:${Port}" }
    'ios'     { "${scheme}://localhost:${Port}" }
    'device'  { "${scheme}://${DeviceIp}:${Port}" }
}

$envContent = @"
# Auto-generated by run_with_backend.ps1 — co the sua tay sau do
API_BASE_URL=$apiBaseUrl
JWT_ISSUER=healthpath
GOOGLE_CLIENT_ID=
FACEBOOK_APP_ID=
"@

Set-Content -Path .env -Value $envContent -Encoding utf8
Write-Host ">>> Da ghi .env voi API_BASE_URL=$apiBaseUrl" -ForegroundColor Green

flutter pub get
flutter run
